{"version":3,"sources":["components/AlertRenderer/ConferenceCallAlert/i18n/ko-KR.ts"],"names":["conferenceCallErrors","bringInFailed","makeConferenceFailed","terminateConferenceFailed","removeFromConferenceFailed","callIsRecording"],"mappings":";;;;;;;;;AAAA;;;;;;;;mFAEGA,kCAAqBC,a,EAAgB,6C,0CACrCD,kCAAqBE,oB,EAAuB,6C,0CAC5CF,kCAAqBG,yB,EAA4B,8C,0CACjDH,kCAAqBI,0B,EAA6B,8C,0CAClDJ,kCAAqBK,e,EAAkB,oC,2BAG1C;AACA;AACA;AACA;AACA","sourcesContent":["import conferenceCallErrors from '@ringcentral-integration/commons/modules/ConferenceCall/conferenceCallErrors';\nexport default {\n  [conferenceCallErrors.bringInFailed]: \"예기치 않은 오류로 인해 통화를 병합하지 못했습니다. 나중에 다시 시도하세요.\",\n  [conferenceCallErrors.makeConferenceFailed]: \"예기치 않은 오류로 인해 통화를 병합하지 못했습니다. 나중에 다시 시도하세요.\",\n  [conferenceCallErrors.terminateConferenceFailed]: \"예기치 않은 오류로 인해 전화 회의를 끊지 못했습니다. 나중에 다시 시도하세요.\",\n  [conferenceCallErrors.removeFromConferenceFailed]: \"예기치 않은 오류로 인해 참가자를 제거하지 못했습니다. 나중에 다시 시도하세요.\",\n  [conferenceCallErrors.callIsRecording]: \"통화 녹음이 진행 중입니다. 녹음을 중지하고 다시 시도하세요.\"\n};\n\n// @key: @#@\"[conferenceCallErrors.bringInFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.makeConferenceFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.terminateConferenceFailed]\"@#@ @source: @#@\"Failed to hangup the conference due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.removeFromConferenceFailed]\"@#@ @source: @#@\"Failed to remove the participant due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.callIsRecording]\"@#@ @source: @#@\"Call recording in progress. Please stop recording and try again.\"@#@\n"],"file":"ko-KR.js"}