{"version":3,"sources":["components/AlertRenderer/ConferenceCallAlert/i18n/zh-CN.ts"],"names":["conferenceCallErrors","bringInFailed","makeConferenceFailed","terminateConferenceFailed","removeFromConferenceFailed","callIsRecording"],"mappings":";;;;;;;;;AAAA;;;;;;;;mFAEGA,kCAAqBC,a,EAAgB,sB,0CACrCD,kCAAqBE,oB,EAAuB,sB,0CAC5CF,kCAAqBG,yB,EAA4B,wB,0CACjDH,kCAAqBI,0B,EAA6B,uB,0CAClDJ,kCAAqBK,e,EAAkB,kB,2BAG1C;AACA;AACA;AACA;AACA","sourcesContent":["import conferenceCallErrors from '@ringcentral-integration/commons/modules/ConferenceCall/conferenceCallErrors';\nexport default {\n  [conferenceCallErrors.bringInFailed]: \"由于意外错误，合并通话失败。请稍后重试。\",\n  [conferenceCallErrors.makeConferenceFailed]: \"由于意外错误，合并通话失败。请稍后重试。\",\n  [conferenceCallErrors.terminateConferenceFailed]: \"由于意外错误，挂断电话会议失败。请稍后重试。\",\n  [conferenceCallErrors.removeFromConferenceFailed]: \"由于意外错误，移除参与者失败。请稍后重试。\",\n  [conferenceCallErrors.callIsRecording]: \"正在通话录音。请停止录音并重试。\"\n};\n\n// @key: @#@\"[conferenceCallErrors.bringInFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.makeConferenceFailed]\"@#@ @source: @#@\"Failed to merge the calls due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.terminateConferenceFailed]\"@#@ @source: @#@\"Failed to hangup the conference due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.removeFromConferenceFailed]\"@#@ @source: @#@\"Failed to remove the participant due to unexpected errors. Please try again later.\"@#@\n// @key: @#@\"[conferenceCallErrors.callIsRecording]\"@#@ @source: @#@\"Call recording in progress. Please stop recording and try again.\"@#@\n"],"file":"zh-CN.js"}